import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Prisma contract artifacts are generated by `prisma contract emit`.
    "prisma/contract.d.ts",
    "prisma/contract.json",
    "migrations/**",
    // Vendored agent skill files (Prisma upgrade recipes) are upstream copies,
    // not project code: linting them only reports their own style.
    ".agents/**",
    ".claude/**",
    ".cursor/**",
    ".devin/**",
    ".opencode/**",
  ]),
]);

export default eslintConfig;
