import { siteConfig } from "@/lib/site.config";
import type { Locale } from "@/lib/i18n/config";

export const OG_IMAGE_WIDTH = 1200;
export const OG_IMAGE_HEIGHT = 630;

/**
 * URL of the branded card generated by `app/[lang]/opengraph-image.tsx`.
 *
 * `openGraph.images` needs to be explicit on pages that declare their own
 * `openGraph` object: those replace the inherited file-convention image rather
 * than merging with it, which would leave them with no image at all.
 */
export function defaultOgImageUrl(locale: Locale): string {
  return `${siteConfig.url}/${locale}/opengraph-image`;
}